[package]
name = "crash_hook"
description = "Hook for crashing the process"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
pipe_com = { workspace = true }
msg_protocol = { workspace = true }
dll_injector = { workspace = true }

windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
] }

[lints]
workspace = true
